// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS-rmWlXp3TIE-ZxVYtKKoFbEuAqOeWu8',
    appId: '1:933394847272:web:0b977db5c18e083102c71d',
    messagingSenderId: '933394847272',
    projectId: 'kaizen-8ac25',
    authDomain: 'kaizen-8ac25.firebaseapp.com',
    storageBucket: 'kaizen-8ac25.appspot.com',
    measurementId: 'G-CGJ9JPEH74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvXQeVyQ62m18lTmSd-j0rjdVJO67ksOk',
    appId: '1:933394847272:android:9ef625180ebd12b202c71d',
    messagingSenderId: '933394847272',
    projectId: 'kaizen-8ac25',
    storageBucket: 'kaizen-8ac25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWCkGO4DTZA2Q8nDO6JP_A0B3ZeHFogAg',
    appId: '1:933394847272:ios:d252e659b9ed94ea02c71d',
    messagingSenderId: '933394847272',
    projectId: 'kaizen-8ac25',
    storageBucket: 'kaizen-8ac25.appspot.com',
    iosBundleId: 'com.example.kaizen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWCkGO4DTZA2Q8nDO6JP_A0B3ZeHFogAg',
    appId: '1:933394847272:ios:d252e659b9ed94ea02c71d',
    messagingSenderId: '933394847272',
    projectId: 'kaizen-8ac25',
    storageBucket: 'kaizen-8ac25.appspot.com',
    iosBundleId: 'com.example.kaizen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS-rmWlXp3TIE-ZxVYtKKoFbEuAqOeWu8',
    appId: '1:933394847272:web:066e2e95bd050eb302c71d',
    messagingSenderId: '933394847272',
    projectId: 'kaizen-8ac25',
    authDomain: 'kaizen-8ac25.firebaseapp.com',
    storageBucket: 'kaizen-8ac25.appspot.com',
    measurementId: 'G-6TW1LJJK12',
  );
}
